# -*- coding: utf-8 -*-
"""Copy of AT - Lesson 13 - Project_Question Copy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KE9JOFq7Wek0M2vtzGaOCBBg8HKMUSQ9

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

  1.  Python List II
  3.  Pandas Series

---

#### Getting Started:

1. Follow the next 3 steps to create a copy of this colab file and start working on the project.
     
2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project13** format.

4. Now, write your code in the prescribed code cells.

### Activities

#### Activity 1.1: Pandas Series containing Random Integers

Create a Pandas series containing 40 random integers between 130 and 145. Print this series.
"""

# Create Pandas series
import pandas as pd
import numpy as np

# create a Pandas series with 40 random integers between 130 and 145
s = pd.Series(np.random.randint(130, 146, size=40))

# print the series
print(s)

"""---

#### Activity 1.2: Calculate Mean and Median

Calculate the mean value and median value of the above Pandas series.
"""

# Calculate the mean and median value
import pandas as pd
import numpy as np


# calculate the mean value
mean_value = s.mean()
print("Mean value: ", mean_value)

# calculate the median value
median_value = s.median()
print("Median value: ", median_value)

"""---

#### Activity 1.3: Find Minimum and Maximum

Find the minimum and maximum value in the above Pandas series.
"""

# Find minimum and maximum value in the above Pandas series
import pandas as pd
import numpy as np

# find the minimum and maximum value in the series
min_val = s.min()
max_val = s.max()

# print the minimum and maximum value
print("Minimum value:", min_val)
print("Maximum value:", max_val)

"""---

#### Activity 1.4: Arrange in Descending Order

Arrange the values in descending order and print the last five rows of the series.
"""

# Arrange the values in descending order and print the last five rows
# sort the series in descending order
s_desc = s.sort_values(ascending=False)

# print the last five rows of the sorted series
print(s_desc.tail(5))

"""---

#### Activity 2: Find whether Two Lines are Parallel

Given two lines, determine whether they are parallel or not.
Lines are represented using a list [a, b, c] which corresponds to the straight line $ax+by=c$.



**Hints:**
- Two lines are parallel if their slopes are equal.

- A line in the form of $ax+by=c$ has slope $\frac {-a}{b}$.
- Ignore the minus $(-)$ sign. Just calculate $\frac {a}{b}$ for both lines and find out whether they are equal or not.


**Example:**
```
line1 = [2,3,4]
line2 = [4,6,8]

Are lines parallel?
True
```
"""

# Two lines are parallel or not
def are_parallel(line1, line2):
    slope1 = line1[0]/line1[1]
    slope2 = line2[0]/line2[1]

    return slope1 == slope2

line1 = [2,3,4]
line2 = [4,6,8]

if are_parallel(line1, line2):
    print("Lines are parallel")
else:
    print("Lines are not parallel")

"""---

### How To Submit The Project

Follow the steps described below to submit the project.
1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.
  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>
2. In the dialog box, click on the **Copy link** button. Make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>
3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project13**) of the notebook will get copied
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>
4. Go to your dashboard and click on the **My Projects** option.
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>
5. Click on the **View Project** button for the project you want to submit.
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>
6. Click on the **Submit Project Here** button.
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>
7. Past the link to the project named as **YYYY-MM-DD_StudentName_Project13** in the URL box and then click on the **Submit** button.
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""